export const Route = {
  // Root
  SPLASH: 'Splash',
  WELCOME: 'Welcome',
  SIGNUP: 'Signup',
  SIGNIN: 'Signin',
  FAVORITES: 'FAVORITES',
  MOVIEFILE: 'MOVIEFILE',
  MOVIEDETAILS: 'MOVIEDETAILS',
  WATCHLATERLIST: 'WATCHLATERLIST',
  INFORMATION: 'INFORMATION',

  // Main Tab Navigation
  TAB_HOME: 'TAB_HOME',
  DRAWER_HOME: 'DRAWER_HOME',
};
